### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by Finest** [risk-of-thunder/BepInEx#3]
Hey,
could you pls update to the latest version ?

https://github.com/BepInEx/BepInEx/releases/tag/v5.4.22

**Comment by xiaoxiao921** [comment]
I guess we could, though I don't see an immediate need for this, did you have something in mind specifically?

**Comment by Nebby1999** [comment]
Looking at the releases I think the TomlConverter implementation for Rect is actually a pretty good addition, since that could allow for less cluttered Configs for UI based mods (IE: position and size of certain elements)

**Comment by Hsky17** [comment]
> I guess we could, though I don't see an immediate need for this, did you have something in mind specifically?

Lots of the mods on lethal company don't work without 5.4.22. I can still install manually, but would like to use my mod manager, so I can choose between vanilla and modded.

**Comment by KingEnderBrine** [comment]
This is for Risk of Rain 2, Lethal Company has it's own version of BepInEx.

> > I guess we could, though I don't see an immediate need for this, did you have something in mind specifically?
> 
> Lots of the mods on lethal company don't work without 5.4.22. I can still install manually, but would like to use my mod manager, so I can choose between vanilla and modded.

**Comment by harbingerofme** [comment]
Furthermore, they all do work with .21, they just emit a warning when loaded, which is safe to ignore.
